In [ ]:
#Importing necessary libraries
import pandas as pd
#Uploading files
from google.colab import files
uplodaed=files.upload() 

Saving Sample Dataset.csv to Sample Dataset.csv


In [ ]:
#Reading and printing the whole dataset
df=pd.read_csv("Sample Dataset.csv")
df

created_at  entry_id  ...  Length  Weight
0       2021-06-20 10:21:11 UTC    7645.0  ...    6.55    2.80
1       2021-06-20 10:21:31 UTC    7646.0  ...    6.55    2.80
2       2021-06-20 10:21:51 UTC    7647.0  ...    6.55    2.80
3       2021-06-20 10:22:11 UTC    7648.0  ...    6.55    2.80
4       2021-06-20 10:22:30 UTC    7649.0  ...    6.55    2.80
...                         ...       ...  ...     ...     ...
152204               29/11/2021       NaN  ...   16.38   15.11
152205               30/11/2021       NaN  ...   16.41   15.18
152206                1/12/2021       NaN  ...   16.45   15.21
152207                2/12/2021       NaN  ...   16.49   15.24
152208                4/12/2021       NaN  ...   16.81   15.29

[152209 rows x 11 columns]

In [ ]:
#Find out all the information of the dataset
df.info

<bound method DataFrame.info of                      created_at  entry_id  ...  Length  Weight
0       2021-06-20 10:21:11 UTC    7645.0  ...    6.55    2.80
1       2021-06-20 10:21:31 UTC    7646.0  ...    6.55    2.80
2       2021-06-20 10:21:51 UTC    7647.0  ...    6.55    2.80
3       2021-06-20 10:22:11 UTC    7648.0  ...    6.55    2.80
4       2021-06-20 10:22:30 UTC    7649.0  ...    6.55    2.80
...                         ...       ...  ...     ...     ...
152204               29/11/2021       NaN  ...   16.38   15.11
152205               30/11/2021       NaN  ...   16.41   15.18
152206                1/12/2021       NaN  ...   16.45   15.21
152207                2/12/2021       NaN  ...   16.49   15.24
152208                4/12/2021       NaN  ...   16.81   15.29

[152209 rows x 11 columns]>

In [ ]:
#Find out the shape of the dataset
df.shape

(152209, 11)

In [ ]:
#Find out the size of the dataset
df.size

1674299

In [ ]:
#Find out the columns of the dataset
df.columns

Index(['created_at', 'entry_id', 'Temperature', 'Turbidity DO', 'D0', 'PH',
       'Ammonia', 'Nitrate', 'Population', 'Length', 'Weight'],
      dtype='object')

In [ ]:
#Printing the head or first 5 row of the dataset
df.head()

created_at  entry_id  Temperature  ...  Population  Length  Weight
0  2021-06-20 10:21:11 UTC    7645.0       25.375  ...          75    6.55     2.8
1  2021-06-20 10:21:31 UTC    7646.0       25.375  ...          75    6.55     2.8
2  2021-06-20 10:21:51 UTC    7647.0       25.375  ...          75    6.55     2.8
3  2021-06-20 10:22:11 UTC    7648.0       25.375  ...          75    6.55     2.8
4  2021-06-20 10:22:30 UTC    7649.0       25.375  ...          75    6.55     2.8

[5 rows x 11 columns]

In [ ]:
#Find out the tail or the last 5 row of the dataset
df.tail()

created_at  entry_id  Temperature  ...  Population  Length  Weight
152204  29/11/2021       NaN          NaN  ...          75   16.38   15.11
152205  30/11/2021       NaN          NaN  ...          75   16.41   15.18
152206   1/12/2021       NaN          NaN  ...          75   16.45   15.21
152207   2/12/2021       NaN          NaN  ...          75   16.49   15.24
152208   4/12/2021       NaN          NaN  ...          75   16.81   15.29

[5 rows x 11 columns]

In [ ]:
#Dropping the Nan values of the dataset
df.dropna

<bound method DataFrame.dropna of                      created_at  entry_id  ...  Length  Weight
0       2021-06-20 10:21:11 UTC    7645.0  ...    6.55    2.80
1       2021-06-20 10:21:31 UTC    7646.0  ...    6.55    2.80
2       2021-06-20 10:21:51 UTC    7647.0  ...    6.55    2.80
3       2021-06-20 10:22:11 UTC    7648.0  ...    6.55    2.80
4       2021-06-20 10:22:30 UTC    7649.0  ...    6.55    2.80
...                         ...       ...  ...     ...     ...
152204               29/11/2021       NaN  ...   16.38   15.11
152205               30/11/2021       NaN  ...   16.41   15.18
152206                1/12/2021       NaN  ...   16.45   15.21
152207                2/12/2021       NaN  ...   16.49   15.24
152208                4/12/2021       NaN  ...   16.81   15.29

[152209 rows x 11 columns]>

In [ ]:
#Find out the numerical columns of the dataset
numerical_cols = df.columns[df.dtypes != object]
numerical_cols

Index(['entry_id', 'Temperature', 'Turbidity DO', 'D0', 'PH', 'Ammonia',
       'Nitrate', 'Population', 'Length', 'Weight'],
      dtype='object')

In [ ]:
#Find out the categorical columns of the dataset
categorical_cols=df.columns[df.dtypes!=object]
categorical_cols

Index(['entry_id', 'Temperature', 'Turbidity DO', 'D0', 'PH', 'Ammonia',
       'Nitrate', 'Population', 'Length', 'Weight'],
      dtype='object')

In [ ]:
#Find out the datatypes of each column of the dataset
df.dtypes

created_at       object
entry_id        float64
Temperature     float64
Turbidity DO    float64
D0              float64
PH              float64
Ammonia         float64
Nitrate         float64
Population        int64
Length          float64
Weight          float64
dtype: object

In [ ]:
#Creating a new dataset by dropping unnecessary columns of previous dataset
df1=df.drop(["created_at", "entry_id", "Population"],axis=1)
df1.head()

Temperature  Turbidity DO     D0       PH  Ammonia  Nitrate  Length  Weight
0       25.375         -13.0  0.488  4.28004     0.01    579.0    6.55     2.8
1       25.375         -13.0  0.712  4.26188     0.01    579.0    6.55     2.8
2       25.375         -13.0  0.360  4.27550     0.01    576.0    6.55     2.8
3       25.375         -13.0  0.320  4.25280     0.01    574.0    6.55     2.8
4       25.375         -13.0  0.328  4.26642     0.01    579.0    6.55     2.8

In [ ]:
#Find out unique values of some columns 
df1['Temperature'].unique()

array([  25.375 ,   25.3125,   25.4375,   25.5   ,   24.5625,   24.4375,
         24.5   ,   24.625 ,   24.6875,   24.75  ,   24.8125,   24.875 ,
         24.9375,   25.    ,   24.375 ,   24.3125,   24.25  ,   24.1875,
         24.125 ,   24.0625,   24.    ,   23.9375,   23.875 ,   23.8125,
         23.75  ,   23.6875,   23.625 ,   23.5625,   23.5   ,   23.4375,
         25.0625,   25.125 ,   25.1875,   25.25  ,   25.5625,   25.625 ,
         25.6875,   25.75  ,   25.8125,   25.875 ,   25.9375,   26.    ,
         26.0625,   23.375 ,   23.3125,   23.25  ,   23.1875,   23.125 ,
         26.125 ,   23.0625,   23.    ,   22.9375, -127.    ,   22.875 ,
         22.8125,   22.75  ,       nan])

In [ ]:
#Find out unique values of some columns
df1['Turbidity DO'].unique()

array([-13.,  51.,  49.,  53.,  59.,  61.,  57.,  63.,  62.,  60.,  64.,
        52.,  65.,  58.,  70.,  69.,  54.,  45.,  50.,  48.,  56.,  55.,
        46.,  47.,  41.,  42.,  39.,  43.,  40.,  38.,  36.,  44.,  37.,
        35.,  66.,  68.,  67.,  75.,  32.,  31.,  30.,  29.,  33.,  34.,
        27.,  26.,  25.,  73.,  71.,  72.,  74.,  76.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  84.,  83.,  82.,  79.,  81.,  80.,
        78.,  28.,  24.,  23.,  22.,  21.,  20.,  19.,  17.,  18.,  16.,
        77.,  96.,  94.,  93.,  95.,  98., 100.,  99.,  97.,  13.,   8.,
        11.,  10.,  15.,  12.,   9.,  14.,   7.,   5.,   6.,   3.,   4.,
         1.,   2.,  -1.,   0.,  -3.,  -2.,  -4.,  -5.,  -6.,  -7.,  -9.,
        -8., -11., -10., -12.,  nan])

In [ ]:
#Find out unique values of some columns
df1['D0'].unique()

array([0.488, 0.712, 0.36 , ..., 0.573, 0.628,   nan])

In [ ]:
#Find out unique values of some columns
df1['PH'].unique()

array([ 4.28004,  4.26188,  4.2755 ,  4.2528 ,  4.26642,  4.23918,
        4.25734,  4.23464,  4.30727,  4.2074 ,  4.22556,  4.21648,
        4.38898,  4.21194,  4.20286,  4.19379,  4.19833,  4.18925,
        4.18471,  4.18017,  4.17109,  4.16201,  4.32543,  4.15293,
        4.14385,  4.14839,  5.19701,  5.17885,  5.18339,  5.16069,
        5.15161,  5.14253,  5.16977,  5.16523,  5.11984,  5.1153 ,
        5.13799,  5.13345,  5.09714,  5.12892,  5.11076,  5.08806,
        5.06536,  5.0699 ,  5.07444,  5.06082,  5.07898,  5.05628,
        5.05174,  5.04267,  5.0472 ,  5.03813,  5.03359,  5.01089,
        5.01997,  5.02905,  5.02451,  5.01543,  5.00181,  5.00635,
        5.08352,  5.2424 ,  5.22424,  5.2197 ,  5.23332,  5.22878,
        5.26056,  5.25602,  5.26964,  5.27872,  5.29234,  5.2878 ,
        5.31503,  5.33319,  5.32411,  5.31049,  5.32865,  5.40582,
        5.41036,  5.40128,  5.41944,  5.39674,  5.4149 ,  5.42852,
        5.47845,  5.44214,  5.43306,  5.4376 ,  5.45122,  5.42

In [ ]:
#Find out unique values of some columns
df1['Ammonia'].unique()

array([0.01   , 0.23569, 0.38618, ..., 0.00834, 0.00897,     nan])

In [ ]:
#Find out unique values of some columns
df1['Nitrate'].unique()

array([ 579.,  576.,  574., ..., 2401., 2856.,   nan])

In [ ]:
#Find out correlation of "Length" column with other columns 
correlation_matrix = df1.corr()
correlation_matrix["Length"]

Temperature    -0.145201
Turbidity DO   -0.771884
D0              0.123906
PH             -0.569069
Ammonia        -0.003486
Nitrate         0.720840
Length          1.000000
Weight          0.998916
Name: Length, dtype: float64

In [ ]:
#Find out correlation of "Weight" column with other columns
correlation_matrix = df1.corr()
correlation_matrix["Weight"]

Temperature    -0.141413
Turbidity DO   -0.761862
D0              0.118353
PH             -0.560793
Ammonia        -0.003598
Nitrate         0.710870
Length          0.998916
Weight          1.000000
Name: Weight, dtype: float64

In [ ]:
#Find out the shape of new dataset
df1.shape

(152209, 8)

In [ ]:
#Find out the size of new dataset
df1.size

1217672

In [ ]:
#Printing the whole dataset
df1

Temperature  Turbidity DO     D0  ...  Nitrate  Length  Weight
0            25.375         -13.0  0.488  ...    579.0    6.55    2.80
1            25.375         -13.0  0.712  ...    579.0    6.55    2.80
2            25.375         -13.0  0.360  ...    576.0    6.55    2.80
3            25.375         -13.0  0.320  ...    574.0    6.55    2.80
4            25.375         -13.0  0.328  ...    579.0    6.55    2.80
...             ...           ...    ...  ...      ...     ...     ...
152204          NaN           NaN    NaN  ...      NaN   16.38   15.11
152205          NaN           NaN    NaN  ...      NaN   16.41   15.18
152206          NaN           NaN    NaN  ...      NaN   16.45   15.21
152207          NaN           NaN    NaN  ...      NaN   16.49   15.24
152208          NaN           NaN    NaN  ...      NaN   16.81   15.29

[152209 rows x 8 columns]

In [ ]:
#Find out the data types of new dataset 
df1.dtypes

Temperature     float64
Turbidity DO    float64
D0              float64
PH              float64
Ammonia         float64
Nitrate         float64
Length          float64
Weight          float64
dtype: object

In [ ]:
#Find out the numerical cols of new dataset
numerical_cols1=df1.columns[df1.dtypes!=object]
numerical_cols1

Index(['Temperature', 'Turbidity DO', 'D0', 'PH', 'Ammonia', 'Nitrate',
       'Length', 'Weight'],
      dtype='object')

In [ ]:
#Find out the categorical columns of new dataset
categorical_cols1=df1.columns[df1.dtypes==object]
categorical_cols1

Index([], dtype='object')

In [ ]:
#Importing necessary libraries
import numpy as np
#Creating another new dataset by replacing the positive and negative infinite value with nan and then drop the nan values
df2 = df1.replace([np.inf, -np.inf], np.nan, inplace=True)
df2 = df1.dropna()
#Printing the whole dataset without any nan values
df2

Temperature  Turbidity DO     D0  ...  Nitrate  Length  Weight
0            25.375         -13.0  0.488  ...    579.0    6.55    2.80
1            25.375         -13.0  0.712  ...    579.0    6.55    2.80
2            25.375         -13.0  0.360  ...    576.0    6.55    2.80
3            25.375         -13.0  0.320  ...    574.0    6.55    2.80
4            25.375         -13.0  0.328  ...    579.0    6.55    2.80
...             ...           ...    ...  ...      ...     ...     ...
152174     -127.000         100.0  0.549  ...   1297.0   12.42    8.92
152175     -127.000         100.0  0.555  ...   1376.0   12.42    8.92
152176     -127.000         100.0  0.573  ...   1437.0   12.42    8.92
152177     -127.000         100.0  0.598  ...   1481.0   12.42    8.92
152178     -127.000         100.0  0.628  ...   1514.0   12.42    8.92

[152093 rows x 8 columns]

In [ ]:
#Importing necessary libraries to calculate distance
from scipy.spatial import distance
#Find out the Minkowski distance of "Weight" column with "Temperature" column
mink_dist1 = distance.minkowski(df2["Weight"].astype(float),df2["Temperature"].astype(float),p=100)
print(mink_dist1)
#Find out the Minkowski distance of "Weight" column with "Turbidity DO" column
mink_dist2 = distance.minkowski(df2["Weight"].astype(float),df2["Turbidity DO"].astype(float),p=100)
print(mink_dist2)
#Find out the Minkowski distance of "Weight" column with "Turbidity D0" column
mink_dist3 = distance.minkowski(df2["Weight"].astype(float),df2["D0"].astype(float),p=100)
print(mink_dist3)
#Find out the Minkowski distance of "Weight" column with "PH" column
mink_dist4 = distance.minkowski(df2["Weight"].astype(float),df2["PH"].astype(float),p=100)
print(mink_dist4)
#Find out the Minkowski distance of "Weight" column with "Ammonia" column
mink_dist5 = distance.minkowski(df2["Weight"].astype(float),df2["Ammonia"].astype(float),p=100)
print(mink_dist5)
#Find out the Minkowski distance of "Weight" column with "Nitrate" column
mink_dist6 = distance.minkowski(df2["Weight"].astype(float),df2["Nitrate"].astype(float),p=100)
print(mink_dist6)
#Find out the Minkowski distance of "Weight" column with "Length" column
mink_dist7 = distance.minkowski(df2["Weight"].astype(float),df2["Length"].astype(float),p=100)
print(mink_dist7)


139.33010534938953
99.23413295280082
43.49556314941991
12.310802655108198
inf
inf
4.1684080568423205


/usr/local/lib/python3.7/dist-packages/numpy/linalg/linalg.py:2568: RuntimeWarning: overflow encountered in power
  absx **= ord
/usr/local/lib/python3.7/dist-packages/numpy/linalg/linalg.py:2569: RuntimeWarning: overflow encountered in reduce
  ret = add.reduce(absx, axis=axis, keepdims=keepdims)
